#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypowervm
Version  : 1.1.19
Release  : 4
URL      : https://files.pythonhosted.org/packages/d6/08/e195b39deee51837165554f508a8aa8f611bcf88a6a0e0461af67d072166/pypowervm-1.1.19.tar.gz
Source0  : https://files.pythonhosted.org/packages/d6/08/e195b39deee51837165554f508a8aa8f611bcf88a6a0e0461af67d072166/pypowervm-1.1.19.tar.gz
Summary  : Python binding for the PowerVM REST API
Group    : Development/Tools
License  : Apache-2.0
Requires: pypowervm-license = %{version}-%{release}
Requires: pypowervm-python = %{version}-%{release}
Requires: pypowervm-python3 = %{version}-%{release}
Requires: futures
Requires: lxml
Requires: oslo.concurrency
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pbr
Requires: pyasn1
Requires: pyasn1-modules
Requires: pytz
Requires: requests
Requires: six
Requires: taskflow
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
pypowervm - Python API wrapper for PowerVM
        ==========================================
        
        NOTE
        ----
        Current versions should utilize the local authentication mechanism.  The remote
        authentication mechanism is intended only for development and test purposes for
        the time being.
        
        Overview
        --------
        pypowervm provides a Python-based API wrapper for interaction with IBM
        PowerVM-based systems.
        
        License
        -------
        The library's license can be found in the LICENSE_ file.  It must be
        reviewed prior to use.

%package license
Summary: license components for the pypowervm package.
Group: Default

%description license
license components for the pypowervm package.


%package python
Summary: python components for the pypowervm package.
Group: Default
Requires: pypowervm-python3 = %{version}-%{release}

%description python
python components for the pypowervm package.


%package python3
Summary: python3 components for the pypowervm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pypowervm package.


%prep
%setup -q -n pypowervm-1.1.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543751211
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypowervm
cp LICENSE %{buildroot}/usr/share/package-licenses/pypowervm/LICENSE
cp debian/copyright %{buildroot}/usr/share/package-licenses/pypowervm/debian_copyright
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypowervm/LICENSE
/usr/share/package-licenses/pypowervm/debian_copyright

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
